[build]
    base = "zenduit-app"
    command = "npm run build --configuration production"
    publish = "dist/zenduit-app/browser"

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status  = 200
